spring.datasource.url=jdbc:postgresql://localhost:5432/crowdcivic
spring.datasource.username=postgres
spring.datasource.password=Reddy@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kandimallajashwanthreddy594@gmail.com
spring.mail.password=dnljhljbdxcsofcd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.properties.mail.smtp.from=kandimallajashwanthreddy594@gmail.com

app.otp.expiry-minutes=10


logging.level.com.civic.crowdcivics=DEBUG
logging.level.org.springframework.mail=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Gemini API Configuration
gemini.api.key=AIzaSyD_NgA-rmJNx_sXKNuk-rrVqbTciLIJs1s
gemini.api.model=gemini-2.5-flash

# SightEngine credentials
sightengine.api.user=58406095
sightengine.api.secret=pPLtxiBpgXrcF7rU7tR2pYqVRd4mb6tu

# Multipart Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
